const colors = {
  light: {
    text: "#1A1A2E",
    tint: "#7C3AED",
    background: "#F8F8FF",
    foreground: "#1A1A2E",
    card: "#FFFFFF",
    cardForeground: "#1A1A2E",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#EDE9FE",
    secondaryForeground: "#1A1A2E",
    muted: "#F0EEF8",
    mutedForeground: "#6B6B9A",
    accent: "#A855F7",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E0D9F5",
    input: "#F0EEF8",
    success: "#10B981",
    warning: "#F59E0B",
    info: "#3B82F6",
    overlay: "rgba(0,0,0,0.5)",
  },
  dark: {
    text: "#F0F0FF",
    tint: "#8B5CF6",
    background: "#0A0A1A",
    foreground: "#F0F0FF",
    card: "#14142A",
    cardForeground: "#F0F0FF",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#1E1E38",
    secondaryForeground: "#C0C0E0",
    muted: "#16162E",
    mutedForeground: "#6868A0",
    accent: "#A855F7",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A4A",
    input: "#1A1A34",
    success: "#10B981",
    warning: "#F59E0B",
    info: "#3B82F6",
    overlay: "rgba(0,0,0,0.75)",
  },
  radius: 14,
};

export default colors;
